import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";


const work_sans = Work_Sans({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "MDX Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={work_sans.className}>
      <body className="body">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <main className="my-main">
            {children}

          </main>
        </ThemeProvider>

      </body>
    </html>
  );
}
